[package]
name = "matplotlib"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.27.2", features = ["auto-initialize"] }
kwargs_builder_derive = { path = "../kwargs_builder_derive" }
ndarray = "0.17.1"
numpy = "0.27"

[[bin]]
name = "matplotlib"
path = "src/main.rs"

[lib]
name = "matplotlib"
path = "src/lib.rs"
