mod shared;

pub mod plot;
pub mod scatter;
pub mod hist;
pub mod imshow;
pub mod fill_between;
pub mod bar;
pub mod axhline;
pub mod axvline;
pub mod text;
pub mod axis;
pub mod xlabel;
pub mod ylabel;
pub mod title;
pub mod xlim;
pub mod ylim;
pub mod xticks;
pub mod yticks;
pub mod legend;
pub mod grid;
pub mod suptitle;
pub mod savefig;
pub mod tight_layout;
pub mod subplots_adjust;

// Re-export builders and functions
pub use plot::{PyPlotBuilder, plot};
pub use scatter::{PyScatterBuilder, ScatterSize, ScatterColor, scatter};
pub use hist::{PyHistBuilder, HistBins, hist};
pub use imshow::{PyImshowBuilder, imshow};
pub use fill_between::{PyFillBetweenBuilder, FillBetweenY2, fill_between};
pub use bar::{PyBarBuilder, BarWidth, BarBottom, ErrorKwValue, bar};
pub use axhline::{PyAxhlineBuilder, axhline};
pub use axvline::{PyAxvlineBuilder, axvline};
pub use text::{PyTextBuilder, text};
pub use axis::{PyAxisBuilder, AxisOption, axis};
pub use xlabel::{PyXlabelBuilder, XLabelLoc, xlabel};
pub use ylabel::{PyYlabelBuilder, YLabelLoc, ylabel};
pub use title::{PyTitleBuilder, TitleLoc, title};
pub use xlim::{PyXlimBuilder, xlim};
pub use ylim::{PyYlimBuilder, ylim};
pub use xticks::{PyXticksBuilder, xticks};
pub use yticks::{PyYticksBuilder, yticks};
pub use legend::{PyLegendBuilder, LegendLoc, LegendAlignment, legend};
pub use grid::{PyGridBuilder, GridWhich, GridAxis, grid};
pub use suptitle::{PySuptitleBuilder, SuptitleHAlign, SuptitleVAlign, suptitle};
pub use savefig::{PySavefigBuilder, savefig};
pub use tight_layout::{PyTightLayoutBuilder, tight_layout};
pub use subplots_adjust::{PySubplotsAdjustBuilder, subplots_adjust};
pub(super) use shared::get_plt;
