mod shared;

pub mod plot;
pub mod scatter;
pub mod hist;
pub mod imshow;
pub mod fill_between;
pub mod bar;
pub mod axhline;
pub mod axvline;
pub mod text;
pub mod axis;
pub mod xlabel;
pub mod ylabel;
pub mod title;
pub mod xlim;
pub mod ylim;
pub mod xticks;
pub mod yticks;
pub mod legend;
pub mod grid;
pub mod suptitle;
pub mod savefig;
pub mod tight_layout;
pub mod subplots_adjust;
pub mod subplots;

// Re-export builders and functions
pub use plot::{plot, PyPlotBuilder};
pub use scatter::{scatter, PyScatterBuilder, ScatterColor, ScatterSize};
pub use hist::{hist, HistBins, PyHistBuilder};
pub use imshow::{imshow, PyImshowBuilder};
pub use fill_between::{fill_between, FillBetweenY2, PyFillBetweenBuilder};
pub use bar::{bar, BarBottom, BarWidth, ErrorKwValue, PyBarBuilder};
pub use axhline::{axhline, PyAxhlineBuilder};
pub use axvline::{axvline, PyAxvlineBuilder};
pub use text::{text, PyTextBuilder};
pub use axis::{axis, AxisOption, PyAxisBuilder};
pub use xlabel::{xlabel, PyXlabelBuilder, XLabelLoc};
pub use ylabel::{ylabel, PyYlabelBuilder, YLabelLoc};
pub use title::{title, PyTitleBuilder, TitleLoc};
pub use xlim::{xlim, PyXlimBuilder};
pub use ylim::{ylim, PyYlimBuilder};
pub use xticks::{xticks, PyXticksBuilder};
pub use yticks::{yticks, PyYticksBuilder};
pub use legend::{legend, LegendAlignment, LegendLoc, PyLegendBuilder};
pub use grid::{grid, GridAxis, GridWhich, PyGridBuilder};
pub use suptitle::{suptitle, PySuptitleBuilder, SuptitleHAlign, SuptitleVAlign};
pub use savefig::{savefig, PySavefigBuilder};
pub use tight_layout::{tight_layout, PyTightLayoutBuilder};
pub use subplots_adjust::{subplots_adjust, PySubplotsAdjustBuilder};
pub use subplots::{subplots};
pub(super) use shared::get_plt;
